name: Run Docker Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -f .dockerfile -t api-testing-project .

      - name: Create allure-results directory
        run: mkdir -p allure-results

      - name: Run tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results api-testing-project pytest test/ --alluredir=/app/allure-results

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
